export const SET_TYPE = "SET_TYPE";
export const SET_SIMPLE_ACTIVE = "SET_SIMPLE_ACTIVE";
export const SET_OPTIONS = "SET_OPTIONS";
export const ACTION_REPLAY = "REPLAY";
export const ADD_COMPLEX_TRANSFORM = "ADD_COMPLEX_TRANSFORM";
export const REMOVE_COMPLEX_TRANSFORM = "REMOVE_COMPLEX_TRANSFORM";
export const SET_COMPLEX_TRANSFORM = "SET_COMPLEX_TRANSFORM";
export const REORDER_COMPLEX_TRANSFORM = "REORDER_COMPLEX_TRANSFORM";;